### ISSUE TITLE
snapshotter: devmapper: Add an automated thinpool creation mode

### ISSUE THREAD

**Issue by sboeuf** [firecracker-microvm/firecracker-containerd#104]
The device mapper implementation of the snapshotter is currently not creating the thinpool by default, and returns an error if the thinpool has not been created beforehand. When users perfectly know what they want to achieve by using device mapper, this approach is completely valid.
But for a user who wants to try out some block based device snapshotter, he does not want to run into pre-configuration steps such as creating thinpools on its own.
That's why I think having in the configuration of the current snapshotter implementation, an option to specify if you want the snapshotter to take care of this step for you could be very useful.
We don't need to advertise this as the most optimized and "production ready" use case, but as a nice way to get started with it.

Issue opened based on the discussion started [here](https://github.com/firecracker-microvm/firecracker-containerd/commit/7fa9f239d25999ed8c13708e3fa589dd659f34e1#r32238628).

**Comment by samuelkarp** [comment]
> > Along with improving this devicemapper-based snapshotter, we're looking at whether we want to take other approaches, like combining image-layers in devicemapper and container-layers with overlay inside the microVM.
>
> That'd be really cool, as you could describe the block layers. But my understanding is that based on what's expected to be returned by the Snapshotter API, the list of mounts will be mounted anyway because that's a list of mounts, but in case of block, you don't want those mounts to happen. So I guess because you're running with containerd-shim-v2, you can afford to do a few assumptions there, but I'm worried this might mean the containerd-shim-v1 will not be compatible with your Snapshotter implementation.

Thanks for the call-out.  We're definitely still in the "just talking about it" stage and haven't started looking at it seriously.  We are focused on finding the right answer for firecracker-containerd, which is using containerd-shim-v2, but if we can build something that has broader applicability we'd like to achieve that as well.

The reason we're looking at alternative approaches is some concerns that have been expressed about devicemapper device activation latency and the effect that it might have on image pull and container launch.  @mxpv has started on a benchmarking effort in https://github.com/firecracker-microvm/firecracker-containerd/pull/89 so we can have more data around what that impact actually looks like.

**Comment by kzys** [comment]
@mxpv Would it make sense to move this issue to containerd?

**Comment by sboeuf** [comment]
@kzys sounds good, feel free to close this one and reference it from the new one in containerd.

**Comment by IRCody** [comment]
@sboeuf: I went ahead and created one on containerd to continue the discussion, linking back to here and the original discussion. I tagged you in the issue also, Thanks!
