### ISSUE TITLE
snapshotter: boltdb needs to rollback when mkfs or create thin pool fails

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker-containerd#107]
Currently when [mkfs](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/snapshotter/devmapper/snapshotter.go#L277) or [create thin pool](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/snapshotter/devmapper/snapshotter.go#L271) encounters an error, it does not rollback the changes to the DB and immediately returns an error. This causes an odd error of failing subsequent calls with `object already exists` due to it already existing in the DB but may not have create the thin pool, yet.The proposed change would be to rollback changes that occurred during `storage.CreateSnapshot`.

**Comment by mxpv** [comment]
Fixed in #106
