### ISSUE TITLE
Propagate namespace setting from shim to agent

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-containerd#119]
Right now, [agent always uses the default namespace](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/agent/service.go#L40) even though the [runtime shim on the host can be configured with a user-specified namespace](https://github.com/containerd/containerd/blob/master/runtime/v2/shim/shim.go#L164).

We need to ensure the two are using a consistent namespace setting.

**Comment by kzys** [comment]
Seems the agent always use the default namespace still. https://github.com/firecracker-microvm/firecracker-containerd/blob/e84a435e52acb36157536b5f3ddba090ed0da789/agent/main.go#L65

**Comment by sipsma** [comment]
Looking back on this, I'm actually no longer convinced this is an issue. In our current model, all the tasks in a given VM have the same namespace.

The actual value of the namespace matters outside the VM because we need to ensure it's kept separate from other VMs in different namespaces (e.g. we need to create directories for the VM that are parameterized by its namespace). However, inside the VM there can only be one namespace, so it actually shouldn't matter what the value is (may as well be the default).

Given the above, I'm going to close this issue, but if there are any objections or other considerations I'm missing please feel free to reopen.
