### ISSUE TITLE
agent: upgrade github.com/mdlayher/vsock

### ISSUE THREAD

**Issue by mdlayher** [firecracker-microvm/firecracker-containerd#135]
Hey folks! I just wanted to let you know that I've landed Go 1.12 runtime network poller support in https://github.com/mdlayher/vsock, meaning that the vsock package should now comply completely with `net.Listener` and `net.Conn`! I'd recommend upgrading the package when possible.

Go 1.11 also still works, but you have to put a loop around the Accept method in order to wait for incoming connections. This is no longer necessary as of Go 1.12.

Please do file an issue if you run into anything unusual!

**Comment by mxpv** [comment]
Hello. Thanks for heads up! That's on my list to take a look at.

**Comment by mdlayher** [comment]
I'm continuing to work on vsock and am nearly finished making it completely compliant with nettest: even returning net.OpError and the like just like a TCP net.Conn would. This work isn't quite done yet, but I'll be tracking it in https://github.com/mdlayher/vsock/issues/29.

I suspect the code will continue to work fine in most cases, but I'm aiming for parity with stdlib connection types as much as possible.

**Comment by mdlayher** [comment]
At this point, I think it's pretty much ready to roll for anything you might need. Let me know if there's anything missing!
