### ISSUE TITLE
TestDMSetup/RemovePool failure in CI

### ISSUE THREAD

**Issue by samuelkarp** [firecracker-microvm/firecracker-containerd#137]
https://buildkite.com/firecracker-microvm/firecracker-containerd/builds/64#91209481-e107-4329-8b9f-b4103bb20491

<details>

```
    --- FAIL: TestDMSetup/RemovePool (5.26s)
        require.go:810: 
            	Error Trace:	dmsetup_test.go:86
            	Error:      	Received unexpected error:
            	            	device or resource busy
            	Test:       	TestDMSetup/RemovePool
            	Messages:   	failed to remove thin-pool
```
</details>

**Comment by kzys** [comment]
It works okay these days?

**Comment by kzys** [comment]
We have removed the snapshotter from our repos (#344). While containerd folks might have the issue, we don't have to track that in this repository.
