### ISSUE TITLE
Implement networking

### ISSUE THREAD

**Issue by IRCody** [firecracker-microvm/firecracker-containerd#14]
Integrate CNI into the appropriate components such that MicroVM-enclosed containers have network access. 

Because Firecracker requires the use of Linux tap devices, many existing CNI plugins will not work. We will need to design one or more plugins to facilitate various network configurations.

**Comment by sipsma** [comment]
Design doc has been posted here: https://github.com/firecracker-microvm/firecracker-containerd/blob/master/docs/networking.md

The logistics of which repo will host the final code for the CNI plugin are currently being worked through right now

**Comment by sipsma** [comment]
* [For right now, the `tc-redirect-tap` plugin is living as a package in the Go SDK](https://github.com/firecracker-microvm/firecracker-go-sdk/tree/master/cni). Eventually, it will most likely live in its own separate repo, but figuring that out is still WIP
* [Support for CNI configuration in the Go SDK](https://github.com/firecracker-microvm/firecracker-go-sdk/issues/126)
  * Once this is merged, I'll be able to send out the PR for support here in Firecracker-containerd
