### ISSUE TITLE
docs: reference a missing TODO.md

### ISSUE THREAD

**Issue by egernst** [firecracker-microvm/firecracker-containerd#19]
Noticed reference to: https://github.com/firecracker-microvm/firecracker-containerd/blob/master/TODO.md

Within https://github.com/firecracker-microvm/firecracker-containerd/tree/master/snapshotter#containerd-firecracker-snapshotter

This link doesn't resolve.

**Comment by IRCody** [comment]
I created a quick PR to remove the dead link. Thanks for letting us know!
