### ISSUE TITLE
Loop device cleanup in CI

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker-containerd#190]
In reference to #184, our CI system will only run one job at a time, which doesn't utilize the full capacity of the CI system. The reason this was done as loop devices kept getting created this would slow down the system and in addition parallel tests would cause each other to time out when trying to utilize the same loop device.

**Comment by sipsma** [comment]
We run in parallel now thanks to #300 , closing as I don't think there's further action for this issue
