### ISSUE TITLE
Define+enforce validation of VMID, Namespace and other API inputs

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-containerd#195]
[VMID is currently unvalidated in terms of length, invalid characters, etc.](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/firecracker-control/local.go#L82).

We should do some validation; it is used to construct filesystem paths and abstract unix socket paths, which is a starting point for defining length contraints and invalid characters (i.e. we probably don't want to allow anything that would result in `../../..` or similar).

We also construct paths from the [containerd namespace](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/internal/vm/dir.go#L37), [container/task ID](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/internal/vm/dir.go#L92), and potentially other parameters provided by clients. We need to do validation on those too (probably even if containerd currently has some form of validation on them for an extra layer of assurance). We should audit our codebase for any other examples of user inputs being used to construct paths.

**Comment by samuelkarp** [comment]
Reopening since #205 only covered the VM ID and not the containerd namespace or container/task ID inputs.

**Comment by mxpv** [comment]
Addressed in https://github.com/firecracker-microvm/firecracker-containerd/pull/218 . Now it validates all path related IDs (vm id, container id, and namespace).
