### ISSUE TITLE
runtime/service_integ_test: Shouldn't use lsblk to validate

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker-containerd#203]
We currently use `lsblk` to validate that the stub drives have been created. However, we are `lsblk` is tied to the `Debian` image and the output, which we use for validation, is prone to change. A better and longer term solution would be write a piece of software that does something similarly to `lsblk` but has a strict output. This executable should be injected into the root image.

Something like:
```
Name        Size          StubDrive
vda         1M            N
vdb         512B          Y
```

**Comment by nmeyerhans** [comment]
We can just use a module like https://godoc.org/github.com/google/cadvisor/utils/sysfs without building a standalone tool and parsing its output.

**Comment by kzys** [comment]
Doesn't it still need a standalone tool, to use something like cadvisor/utils/sysfs inside the container from the integration tests?

**Comment by sipsma** [comment]
Another possibility to consider is to just use `ls` and `cat` on some dirs and files under `/sys` from within the container, write that output to stdout and then parse it from the integ test code. That's the general idea behind some of the other integ tests: https://github.com/firecracker-microvm/firecracker-containerd/blob/d2a7b17a0f8b89c90cff28b509fb051452a982e5/runtime/service_integ_test.go#L279

`ls` and `cat` are essentially universal and are highly unlikely to change. `/sys` is also not prone to changing given it's a kernel interface.

**Comment by kzys** [comment]
I like the idea. Checking `/sys/block/$name/size` returns what @xibz mentioned, except for StubDrive. Stub drives are our own concept and the guest kernel (or even Firecracker?) doesn't know about, I think.

One of the alternatives is checking the output of mount(8) in addition to sysfs to figure out the rootfs' device. Then we can assume that others are stub drives.

**Comment by sipsma** [comment]
I suspect we could also identify the stub drives by just running something like `head -c <num bytes> /dev/sdX` and inspecting the output to determine if `/dev/sdX` has the contents expected of a stub drive.

At least on my ec2 instance, I'm able to run `head` against block devices under `/dev` successfully. `head` is another coreutil, so I'd feel comfortable having a dependency on it for the tests in addition to `cat` and `ls`.

**Comment by kzys** [comment]
You are right. I didn't know the magic bytes.

https://github.com/firecracker-microvm/firecracker-containerd/blob/2578f3df9d899aa48decb39c9f7f23fa41635ede/internal/common.go#L67

**Comment by kzys** [comment]
Hmm, I cannot access /dev/vdX from Firecracker's guest OS.

```
root@microvm:/# ls /dev
console  core  fd  full  mqueue  null  ptmx  pts  random  shm  stderr  stdin  stdout  tty  urandom  zero
root@microvm:/#
```

**Comment by sipsma** [comment]
@kzys Did you bind mount the microvm's `/dev` to the container's `/dev`? If not, RunC will by default create its own `/dev` for the container which won't include block devices like `/dev/vdX`

**Comment by kzys** [comment]
I see. Can I just mount /dev as /dev?

```
% sudo ctr --address /run/firecracker-containerd/containerd.sock --debug run --snapshotter firecracker-naive --runtime aws.firecracker --mount type=bind,src=/dev,dst=/dev --tty --rm docker.io/library/debian:latest sh
ctr: failed to create task: rpc error: code = Unknown desc = failed to create runc shim for task: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/dev\\\" to rootfs \\\"/container/sh/rootfs\\\" at \\\"/container/sh/rootfs/dev\\\" caused \\\"no such device\\\"\"": unknown
```

**Comment by sipsma** [comment]
Interesting... with other runtimes have been able to do that successfully, but obviously something else must be happening here with ours. The error message you're getting, `no such device` isn't too helpful either unfortunately... A couple things that come to mind to try:
1. Try running with `--privileged`
2. Try mounting to somewhere else in the container like `/dev:/hostdev` or something
3. If containerd's syntax supports it, try doing using `rbind` instead of `bind` in the `--mount` argument. This will ensure you are picking up all the mounts under /dev like pts and shm. I've occasionally seen this fix mounts that are failing for mysterious reasons (likely related to mount propagation issues)

I can think of a few more obscure things to try if those don't work too, let me know. I'll also go look at the relevant RunC code to see if that reveals any obvious causes.

**Comment by sipsma** [comment]
Ah okay, so, looking at `[mount(2)](http://man7.org/linux/man-pages/man2/mount.2.html)`, `ENODEV` can be returned when `filesystemtype not configured in the kernel`.

This makes me suspect this may be a more mundane syntax error where `bind` is just not being sent as the mount type as expected. I would also trying using the full syntax including `options`, i.e. `--mount type=bind,src=/dev,dst=/dev,options=rbind,rw`

**Comment by kzys** [comment]
Thanks. Yes! options=bind works

```
ctr --address /run/firecracker-containerd/containerd.sock --debug run --snapshotter firecracker-naive --runtime aws.firecracker --mount type=bind,src=/dev,dst=/hostdev,options=bind --tty --rm docker.io/library/debian:latest sh2
root@microvm:/# ls /dev
console  core  fd  full  mqueue  null  ptmx  pts  random  shm  stderr  stdin  stdout  tty  urandom  zero
root@microvm:/# ls /hostdev
block            initctl       loop6               pts       tty10  tty2   tty29  tty38  tty47  tty56  tty8     vsock
char             kmsg          loop7               random    tty11  tty20  tty3   tty39  tty48  tty57  tty9     zero
console          log           mem                 shm       tty12  tty21  tty30  tty4   tty49  tty58  ttyS0
core             loop-control  memory_bandwidth    snapshot  tty13  tty22  tty31  tty40  tty5   tty59  urandom
cpu              loop0         mqueue              stderr    tty14  tty23  tty32  tty41  tty50  tty6   vcs
cpu_dma_latency  loop1         net                 stdin     tty15  tty24  tty33  tty42  tty51  tty60  vcs1
disk             loop2         network_latency     stdout    tty16  tty25  tty34  tty43  tty52  tty61  vcsa
fd               loop3         network_throughput  tty       tty17  tty26  tty35  tty44  tty53  tty62  vcsa1
full             loop4         null                tty0      tty18  tty27  tty36  tty45  tty54  tty63  vda
hugepages        loop5         ptmx                tty1      tty19  tty28  tty37  tty46  tty55  tty7   vdb
```

**Comment by sipsma** [comment]
Awesome! I actually feel this is something containerd and/or runc should handle more gracefully with a better error case, but would have to look through their code more to see if that's feasible

**Comment by kzys** [comment]
Nah, even the guest OS can have the files, accessing the files are not permitted, even with `--privileged`

```
root@microvm:/# cat /hostdev/vda
cat: /hostdev/vda: Operation not permitted
```

I will take a look further, but may not needed for fixing this issue.

**Comment by sipsma** [comment]
@kzys Wow, yeah I just tried it and get the same EPERM even when trying to open what I know to be an unused stub drive (`/dev/vdc` from a privileged container running off of `/dev/vdb`). Confirmed with strace that it's trying to open `/dev/vdc` readonly and confirmed from /proc/self/status that that container is running with a full set of capabilities... I also get EPERM when I tried to mount `/dev/vdc` from within the container. 

I am not sure, but I wonder if there is some enforcement in the kernel that you must be in the original mount namespace of the host (in this case the guest os) in order to even do a read on block devices like those. If so, I've managed in the past to start up a container via runc that did not change mount namespace from the host (and thus no custom rootfs), but it's extremely hacky/fragile and required my own `config.json`.

Given all that, I agree it may just not be worth trying to actually verify the magic bytes are there. For now, just verifying the size is 512 bytes may be enough.

**Comment by sipsma** [comment]
Okay, I finally figured this out, it was a cgroup issue all along. Even with `--privileged`, our containers are getting created in a cgroup that doesn't allow reads on the `/dev/vdX` devices.

According to `ctr run --help`, we should be able to disable cgroups for the container by setting `--cgroup ""`. However, that just doesn't work in practice from my testing. I am going to open an issue for our repo to determine if we are failing to propagate cgroup settings or if this is a containerd issue.

However, I was able to work around that temporarily for testing by doing the following (which is admittedly completely absurd):
```
root@15b55938792b:/# ctr run --snapshotter firecracker-naive --runtime aws.firecracker --privileged --tty --mount type=bind,src=/,dst=/host,options=rbind:rw docker.io/library/debian:latest thisoneworks chroot /host /bin/sh
/ # echo $$ > /sys/fs/cgroup/devices/tasks
/ # head -c100 /dev/vdc
ױstub1/ #
```
I also had to temporarily make a local change to force there to always be multiple stub drives even when creating a single container VM (again, just for testing this).

So, I think it's worth seeing if you can easily disable cgroups for the container when using the Go containerd API (as opposed to `ctr`). If the Go API allows us to do that easily, then I think we may as well test the contents of the stub drive. If not, then we can just fall back to only testing the size again until we figure out why disabling cgroups doesn't work.

**Comment by kzys** [comment]
Thanks for the investigation! Yes. `ctr run` has --cgroup, but nobody is referencing the flag later apparently :)

https://github.com/containerd/containerd/blob/577872fda5b40c32c2f9023b6bff583941d97288/cmd/ctr/commands/run/run.go#L114
