### ISSUE TITLE
Unable to list tasks via ctr when running a VM

### ISSUE THREAD

**Issue by mxpv** [firecracker-microvm/firecracker-containerd#215]
There is something wrong with context while attempting to list tasks using `ctr`.

Steps:
1. Run
```
sudo ctr --address /run/firecracker-containerd/containerd.sock --namespace test \
  run --snapshotter firecracker-naive --runtime aws.firecracker --tty \
  docker.io/library/busybox:latest busybox-test1
```
You'll get in a busy-box console

2. Open second console and run
```
sudo ctr --address /run/firecracker-containerd/containerd.sock --namespace test t ls
```

Result:
The command hangs
containerd console outputs shows:
```
ERRO[2019-06-27T14:43:30.061411807-07:00] converting task to protobuf error="context canceled: unknown" id=busybox-test1
```

I haven't looked whats going on inside, but I suspect that something about `requestCtx` vs `shimCtx`

**Comment by sipsma** [comment]
I just tried this and was unable to reproduce it, I can run `ctr t ls` successfully:
```
root@8735a946f154:/# ctr t ls
ctr t ls
TASK             PID    STATUS
busybox-test1    953    RUNNING
```

Does it happen every time for you? Are you sure that your `ctr` binary is in sync with the containerd daemon running?

Also, what is the reason you suspect `requestCtx` vs. `shimCtx` here? The error, `converting task to protobuf`, is not something we do explicitly in our code AFAIK.

**Comment by mxpv** [comment]
> Also, what is the reason you suspect requestCtx vs. shimCtx here?

Because request ctx gets cancelled at the end and we get `context canceled: unknown`. But I'm not 100% sure, just thoughts. 

> Are you sure that your ctr binary is in sync with the containerd daemon running?

Built from master, should be in sync.

> Does it happen every time for you?

Yes. At least within same console session, but I haven't tried to restart.

**Comment by sipsma** [comment]
The thing is I'm not even sure `ctr t ls` actually interacts with our shim, I thought it would just interact with the TaskManager plugin built into containerd (not 100% sure about that though).

Is your containerd daemon binary the one with the embedded fc-control plugin? If so, that's might not be master, that's this commit (unless of course you've updated your go.mod locally): https://github.com/sipsma/firecracker-containerd/blob/c0abc8b8ec0d6045f0ed72b2513e9dea13d213c7/go.mod#L9

I started from scratch building everything and am still unable to reproduce it, so I'd double check that if you start from a clean workspace it still is failing.

**Comment by sipsma** [comment]
@mxpv is this still happening?

**Comment by mxpv** [comment]
Nope, I think it's old and no longer relevant.
