### ISSUE TITLE
Change Shim OOM score to +1 of containerd

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-containerd#217]
[Containerd recently updated their reference shim implementations to set the OOM score of the shim to +1 that of the parent containerd process](https://github.com/containerd/containerd/pull/3380):
> This should allow the shim's to
be killed first in an OOM condition but leave the daemon alone for a bit
to help cleanup and manage the containers during this situation.

We should probably make the same change [here](https://github.com/firecracker-microvm/firecracker-containerd/blob/caa5ff0e0bca9b0327b88c328d72cbbc78e36c43/firecracker-control/local.go#L315) but can't quite re-use their code because the fc-control plugin actually runs in the same process as containerd, so it needs to set the shim score to +1 of its own (not of the parent process).

**Comment by praveensastry** [comment]
@sipsma I'd like to contribute to this.

**Comment by sipsma** [comment]
@praveensastry Sounds great, thanks! Please feel free to reach out on this issue or email if we can help clarify anything in the process

**Comment by sipsma** [comment]
Closed by #238
