### ISSUE TITLE
Cannot reuse a Firecracker VM from multiple containers without specifying Container Count

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker-containerd#230]
(From #225)

Probably due to the way we handle stub drives, re-using a Firecracker VM from multiple containers doesn't work due to a mysterious

> Drive "root_drive" could not be found

error.

**Comment by sipsma** [comment]
This specifically happens in situations like the following:
1. Call CreateVM with ContainerCount set to 1
2. Start a container, let it exit and then Delete it.
3. Try to start another container

Besides the extremely unclear error message @kzys mentioned, we should in theory be able to run the second container as the stub drive is no longer being used after the first container is deleted. We could add a feature to support "freeing" stub drives when containers are deleted.

**Comment by kzys** [comment]
Oh, `but may need more changes to actually fix #230` closes the issue since it has "fix #230"...

But, well, I think  #243 is actually better than this one. So I'm not going to reopen this issue.

**Comment by sipsma** [comment]
> Oh, `but may need more changes to actually fix #230` closes the issue since it has "fix #230"...
> 
> But, well, I think #243 is actually better than this one. So I'm not going to reopen this issue.

Ah okay, I had thought that closing it was intentional :-) I think it's better to handle that as a separate issue anyways as it's more of a feature enhancement whereas what you did here was a bug fix.
