### ISSUE TITLE
Send PATCH request in SetVMMetadata API

### ISSUE THREAD

**Issue by haikuoliu** [firecracker-microvm/firecracker-containerd#248]
Hi,

Currently the "SetVMMetadata" API sends PUT request to update the entire MMDS JSON, but we have use cases where we only want to update part of the MMDS, so it would be nice to have PATCH request support in "SetVMMetadata" API.

Let me know if it makes sense,
Thank you 
Haikuo

**Comment by IRCody** [comment]
Closed by #311
