### ISSUE TITLE
Cleaner method of shutdown

### ISSUE THREAD

**Issue by IRCody** [firecracker-microvm/firecracker-containerd#25]
Currently runtime calls stopVM() which forcefully shuts down the VM. Instead we could signal the VM to exit via calling /sbin/reboot which is a more graceful shutdown.

Will need to coordinate with how the runc shim handles shutdown and probably require some re-working of how the agent calls into that.

Right now when running from ctr, ``ctr: rpc error: code = Unknown desc = ttrpc: client shutting down: read vsock:host(2):1222: transport endpoint is not connected: unknown`` is printed every time ctr finishes. We should close down the connection gracefully if possible to avoid this error.

**Comment by mxpv** [comment]
Also blocked by https://github.com/mdlayher/vsock/pull/20
