### ISSUE TITLE
Container Metrics API support

### ISSUE THREAD

**Issue by haikuoliu** [firecracker-microvm/firecracker-containerd#256]
Hi,

Open this issue as a feature request for containerd [Metrics API](https://github.com/containerd/containerd/blob/master/task.go#L177). Additionally, the containerd `Metrics` API doesn't include the network metrics, we would also need the metrics for the network interface attached to the VM, the format could be something similar to `networks` section in [docker stats API](https://docs.docker.com/engine/api/v1.30/#operation/ContainerStats), I guess it could be in a separate firecracker control API:

```
"networks": {
  "eth0": {
    "rx_bytes": 5338,
    "rx_dropped": 0,
    "rx_errors": 0,
    "rx_packets": 36,
    "tx_bytes": 648,
    "tx_dropped": 0,
    "tx_errors": 0,
    "tx_packets": 8
  }
}
```

Let me know if it makes sense, thanks!

**Comment by samuelkarp** [comment]
Are you configuring the network yourself or planning to use [the work that @sipsma is doing](https://github.com/firecracker-microvm/firecracker-go-sdk/pull/125)?  If you're configuring the network yourself (and controlling the host-side network namespace), you should be able to grab those metrics from the network namespace under your control.

**Comment by haikuoliu** [comment]
@samuelkarp yeah you are right, we will configure the network ourself thus the network metrics API is not necessary.

**Comment by samuelkarp** [comment]
Thanks, closing.

**Comment by haikuoliu** [comment]
@samuelkarp just to confirm, do we already support metrics API for disk/cpu/memory? If not I think it's still worthy keeping this issue open

**Comment by aaithal** [comment]
Opening the issue to get answers to https://github.com/firecracker-microvm/firecracker-containerd/issues/256#issuecomment-534797429. @samuelkarp /maintainers, does the firecracker-containerd runtime support metrics API?

**Comment by jtoberon** [comment]
It should. We will test.

**Comment by sipsma** [comment]
@haikuoliu @aaithal I confirmed I was able to successfully call `task.Metrics()` against firecracker-containerd containers. What happens in practice is [containerd calls](https://github.com/containerd/containerd/blob/f01665aa02d8b26c581fdfcc93d837ce3b275edd/services/tasks/local.go#L611) our shim's [`Stats()` API](https://github.com/firecracker-microvm/firecracker-containerd/blob/006b04a2496e6f1426e61c5c3a7b095ae45ce5aa/runtime/service.go#L1208), which gets forwarded to our [VM agent](https://github.com/firecracker-microvm/firecracker-containerd/blob/006b04a2496e6f1426e61c5c3a7b095ae45ce5aa/agent/service.go#L540) and passed to the [runc implementation of Stats()](https://github.com/containerd/containerd/blob/f01665aa02d8b26c581fdfcc93d837ce3b275edd/runtime/v2/runc/v2/service.go#L606). So the metrics will be returned as seen by runc within the MicroVM.

Does that answer all your questions around metrics support?

**Comment by aaithal** [comment]
It does, thanks for confirming!
