### ISSUE TITLE
Don't assert on exact VM rootfs size in integ test

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-containerd#267]
Currently we need to update this number whenever any agent code changes (which results in a different sized VM rootfs in integ tests): https://github.com/firecracker-microvm/firecracker-containerd/blob/5a77bc8dcb0a4953bee03cbbb5f42a2998552a6f/runtime/service_integ_test.go#L554

That's feasible, but a nice enhancement to the test would be to not assert on the size at all since it's the rest of the data there (the stub drives) that we mostly care about testing, not the rootfs.

**Comment by Zyqsempai** [comment]
I will take this one.

**Comment by sipsma** [comment]
@Zyqsempai sounds great, thanks again!

**Comment by Zyqsempai** [comment]
@sipsma Hmm, by the way what would be the best approach here?

**Comment by sipsma** [comment]
@Zyqsempai there's multiple valid ways to do it, but I think the simplest way might be to just skip checking the first 2 lines of the output, which are just headers and then the line for `vda`, the root drive.

What we really care about asserting on in this test case is that the stub drives look right, so that just means asserting on the drives starting at `vdb`.

**Comment by sipsma** [comment]
Closed by #279
