### ISSUE TITLE
How to get shell of VM when using Firecracker 0.18.0?

### ISSUE THREAD

**Issue by haikuoliu** [firecracker-microvm/firecracker-containerd#275]
For Firecracker 0.17.0, as per the [doc](https://github.com/firecracker-microvm/firecracker-containerd/tree/master/tools/image-builder), we can build the rootfs with vsock server and log into the VM using vsock client with `ContextID` from `GetVMInfo`. After upgrading to the latest version of firecracker-containerd and Firecracker 0.18.0, I don't get `ContextID` anymore, I guess something was changed together with the firecracker-containerd vsock support, is the doc still up to date? What would be the new way of getting VM shell if the old solution is not working anymore?

**Comment by sipsma** [comment]
The previous approach doesn't work because Firecracker's vsock implementation now uses unix sockets as endpoints on the host (though still normal `AF_VSOCK` sockets inside the guest).

As for alternatives to explore, @nmeyerhans can chime in with some I was just talking to him about offline.

**Comment by sipsma** [comment]
One option to fallback on is to rely on tools that Firecracker-containerd is agnostic to. Users are, for example, free to install SSHd in their VM's rootfs image and setup VM networking such that you can SSH into the VM (though obviously with care for any security concerns that arise as a result).

I will leave this issue open for investigating whether we can adapt 3rd party tools or write our own new one that allows a shell to be opened over vsock using Firecracker's new host implementation as that certainly would be a convenient debugging utility to have again.
