### ISSUE TITLE
Remove devmapper snapshotter

### ISSUE THREAD

**Issue by mxpv** [firecracker-microvm/firecracker-containerd#318]
The device mapper snapshotter upstreamed to containerd (and released in 1.3), it's more up to date and there are no reasons to keep two versions of the same code. I think it's time to remove it from our repo and rely on containerd.
Plan:
- [x] Add a guide how to create a thin-pool
- [x] Update docs (incl #194)
- [x] Update CI
- [x] Remove code packages
- [x] Remove naive snapshotter switchers from examples and integration tests

**Comment by kzys** [comment]
The CI (BuildKite) is actually using the upstreamed snapshotter.
