### ISSUE TITLE
SetVMMetadata is not working as expected

### ISSUE THREAD

**Issue by haikuoliu** [firecracker-microvm/firecracker-containerd#320]
I am using firecracker v0.18.0 with the latest fc-containerd commit, the following are several formats that I've been used to set the `Metadata` parameter in `SetVMMetadataRequest` and the produced result by curling MMDS endpoint inside firecracker VM:
1. `"{test:data}"` 
    * `curl http://169.254.169.254/` => `{test:data}`
    * `curl http://169.254.169.254/test` => `Resource not found`
2. `"{\"test\":\"data\"}"`
    * `curl http://169.254.169.254/` => `{\"test\":\"data\"}` 
    * `curl http://169.254.169.254/test` => `Resource not found`
3. `"{\\"test\\":\\"data\\"}"`
    * `curl http://169.254.169.254/` => `{\\"test\\":\\"data\\"}`
    * `curl http://169.254.169.254/test` => `Resource not found`

I believe case 2 above is the format that I saw in [TestUpdateVMMetadata_Isolated](https://github.com/firecracker-microvm/firecracker-containerd/blob/b71c02bcc5ebddebc70c9f1fa67af6637b631e88/runtime/service_integ_test.go#L1007). An observation I've seen is no matter what json string I pass in the `SetVMMetadata` API, only the root path `http://169.254.169.254/` are set for that json string.

To ensure my firecracker and my test environment are working, I also use the following raw firecracker API to set MMDS:

```
curl --unix-socket $socket -i \
     -X PUT "http://localhost/mmds" \
     -H  "accept: application/json" \
     -H  "Content-Type: application/json" \
     -d "{
            \"test\": \"data\"
         }"
```

And the result:
  * `curl http://169.254.169.254/` => `test`
  * `curl http://169.254.169.254/test` => `data`

Can you investigate this? An ec2 integration test for the following cases would be helpful for client to integrate and to ensure things are not breaking:
1. `curl http://169.254.169.254/test` => data
2. `curl http://169.254.169.254/get_json_string` => {"key": "value"}

**Comment by IRCody** [comment]
I added #321 where I [expanded](https://github.com/firecracker-microvm/firecracker-containerd/pull/321/commits/fa5df13ee269a4643ac8b532a6052d441dbfe09a#diff-5e5cc717e2803524fb4d62e8faea3689R1099) the tests in TestUpdateVMMetadata_Isolated to include testing an entry that seems to be working.

Can you provide the code or code sample that matches the way you are sending the string so I can try to reproduce the issue?

> Can you investigate this? An ec2 integration test for the following cases would be helpful for client to integrate and to ensure things are not breaking:
> 
>     1. curl http://169.254.169.254/test => data
>     2. curl http://169.254.169.254/get_json_string => {"key": "value"}

The PR should address 1. For 2 I'm not aware of get_json_string, is that something exposed by firecracker?

**Comment by haikuoliu** [comment]
Thanks @IRCody, looks like it works for you, I will do more tests in my side and let you know

**Comment by IRCody** [comment]
> "{\"test\":\"data\"}"
> 
>     curl http://169.254.169.254/ => {\"test\":\"data\"}
>     curl http://169.254.169.254/test => Resource not found

I had similar issue to this at some point when playing around with this at one point. I'd be interested to take a look at the specifics of how you're calling the API to make sure we didn't miss a case we should be handling.

**Comment by haikuoliu** [comment]
Below is my test code (ignore the bad format), basically I start a VM with a network interface, and start a privileged container with host network mode in the VM, and I exec into the container using containerd ctl to do `curl http://169.254.169.254/test`, let me know if you find anything.
```
package main

import (
	"context"
	"log"
	"time"
	"flag"
	"os/exec"

	"github.com/containerd/containerd"
	"github.com/containerd/containerd/cio"
	"github.com/containerd/containerd/namespaces"
	"github.com/containerd/containerd/oci"
	"github.com/google/uuid"
	specs "github.com/opencontainers/runtime-spec/specs-go"

	fcclient "github.com/firecracker-microvm/firecracker-containerd/firecracker-control/client"
	"github.com/firecracker-microvm/firecracker-containerd/proto"
	"github.com/firecracker-microvm/firecracker-containerd/runtime/firecrackeroci"
)

const (
	kernelArgs       = "console=ttyS0 noapic reboot=k panic=1 pci=off nomodules rw"
	containerdAddress      = "/run/firecracker-containerd/containerd.sock"
	containerdTTRPCAddress = containerdAddress + ".ttrpc"
	namespaceName          = "fn"
)

const metadata = "{\"a\":\"b\"}"

func main() {
	var tapName = flag.String("tap", "tap1", "tap device name")

	err := run(*tapName)
	if err != nil {
		log.Printf("Failed: %v", err)
	}
}

func run(tapname string) error {
	log.Println("Creating containerd client")
	client, err := containerd.New(containerdAddress)
	if err != nil {
		return err
	}

	defer client.Close()
	log.Println("Created containerd client")

	ctx := namespaces.WithNamespace(context.Background(), namespaceName)
	image, err := client.Pull(ctx, "docker.io/library/oraclelinux:latest",
		containerd.WithPullUnpack,
		containerd.WithPullSnapshotter("devmapper"),
	)
	if err != nil {
		return err
	}

	fcClient, err := fcclient.New(containerdTTRPCAddress)
	if err != nil {
		return err
	}

	defer fcClient.Close()

//	vmID := uuid.New().String()
	vmID := "id1"

	err = createTapDevice(ctx, tapname)
	if err != nil {
		return err
	}

	interfaces := []*proto.FirecrackerNetworkInterface{
		&proto.FirecrackerNetworkInterface{
			AllowMMDS: true,
			StaticConfig: &proto.StaticNetworkConfiguration{
				MacAddress: "AA:FC:00:00:00:01",
				HostDevName: tapname,
			},
		},
	}
	
	createVMRequest := &proto.CreateVMRequest{
		//KernelArgs: kernelArgs,
		VMID: vmID,
		NetworkInterfaces: interfaces,
	}

	_, err = fcClient.CreateVM(ctx, createVMRequest)
	if err != nil {
		return err
	}

	setVMMetadataRequest := &proto.SetVMMetadataRequest{
		VMID:     vmID,
		Metadata: metadata,
	}
	_, err = fcClient.SetVMMetadata(ctx, setVMMetadataRequest)
	if err != nil {
		panic(err)
	}
	log.Println("mmds is set")

	defer func() {
		_, stopErr := fcClient.StopVM(ctx, &proto.StopVMRequest{VMID: vmID})
		if stopErr != nil {
			log.Printf("failed to stop VM, err: %v\n", stopErr)
		}
		if err == nil {
			err = stopErr
		}
	}()

	args := make([]string, 0)
	args = append(args, "sh")
	args = append(args, "-c")
	args = append(args, "ip addr add 172.16.0.2/24 dev eth0 && ip link set eth0 up && ip route add default via 0.0.0.0 dev eth0 && sleep 30000000")
	cid := uuid.New().String()
	log.Printf("Successfully pulled %s image\n", image.Name())
	container, err := client.NewContainer(
		ctx,
		cid,
		containerd.WithSnapshotter("devmapper"),
		containerd.WithNewSnapshot(cid, image),
		containerd.WithNewSpec(
			oci.WithPrivileged,
			oci.WithHostNamespace(specs.NetworkNamespace),
			oci.WithHostHostsFile,
			oci.WithHostResolvconf,
			oci.WithImageConfig(image),
			firecrackeroci.WithVMID(vmID),
			oci.WithProcessArgs(args...),
		),
		containerd.WithRuntime("aws.firecracker", nil),
	)
	if err != nil {
		return err
	}
	defer container.Delete(ctx, containerd.WithSnapshotCleanup)

	task, err := container.NewTask(ctx, cio.NewCreator(cio.WithStdio))
	if err != nil {
		return err

	}
	defer task.Delete(ctx)

	log.Printf("Successfully created task: %s for the container\n", task.ID())
	_, err = task.Wait(ctx)
	if err != nil {
		return err

	}

	log.Println("Completed waiting for the container task")
	if err := task.Start(ctx); err != nil {
		return err

	}

	log.Println("Successfully started the container task")

	getVMInfoRequest := &proto.GetVMInfoRequest{
                VMID: vmID,
        }
        res, err := fcClient.GetVMInfo(ctx, getVMInfoRequest)
        if err != nil {
                return err
        }
	log.Printf("vminfo: %v", res)

	time.Sleep(3000 * time.Minute)

	return nil
}


func createTapDevice(ctx context.Context, tapName string) error {
	err := exec.CommandContext(ctx, "ip", "tuntap", "add", tapName, "mode", "tap").Run()
	if err != nil {
		return err
	}

	err = exec.CommandContext(ctx, "ip", "addr", "add", "172.16.0.1/24", "dev", tapName).Run()
	if err != nil {
		return err
	}

	err = exec.CommandContext(ctx, "ip", "link", "set", tapName, "up").Run()
	if err != nil {
		return err
	}

	return nil
}

```

**Comment by haikuoliu** [comment]
Thanks @IRCody , the latest commit works for me, close this issue.
