### ISSUE TITLE
Determine how agent and runc should be embedded into the microvm

### ISSUE THREAD

**Issue by samuelkarp** [firecracker-microvm/firecracker-containerd#33]
firecracker-microvm depends on three components to be inside the microvm: the agent (communicating across the `vsock`s for control and stdio), containerd's runc shim (supervising runc), and runc (running the requested container).  We need to determine how we want those components to be made available inside the microvm: embedded in the microvm-guest image, added as a separate device, or something else.

**Comment by nmeyerhans** [comment]
Automation of image creation from #153 covers this. Closing.
