### ISSUE TITLE
Run CI/CD tests on AL2

### ISSUE THREAD

**Issue by haikuoliu** [firecracker-microvm/firecracker-containerd#341]
We will run firecracker-containerd on AL2, so it would be good if you can run integration tests on AL2, that will help us debug when we run into some issue.

Thanks,
Haikuo

**Comment by kzys** [comment]
I was trying to run integration tests on Amazon Linux 2 by using Docker, but we would need a real Amazon Linux 2 host, according to #345,

**Comment by kzys** [comment]
@xbiz has been working on this task. We are going to have an Amazon Linux 2 host soon for running our tests.

**Comment by kzys** [comment]
@xibz Can we close this issue now? We have https://buildkite.com/firecracker-microvm/firecracker-containerd-al2/.

**Comment by xibz** [comment]
Yea, closibg

**Comment by kzys** [comment]
@xibz Oh, can you make the pipeline public?

**Comment by xibz** [comment]
@kzys - done
