### ISSUE TITLE
Re-enable `-race` in agent builds

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-containerd#357]
We recently started running our CI tests with binaries where `-race` was enabled, but it seems in the latest commits that `agent` is no longer running with it.

Back when it was enabled, it seemed to uncover an actual bug in one of our dependencies, so we should consider re-enabling it as it has already provided pretty significant value: https://github.com/containerd/go-runc/pull/58

**Comment by IRCody** [comment]
I'm not sure this is true anymore. iiuc the -race flag is being passed from EXTRAGOARGS env var. Looking at a test run it seems like it's running with -race enabled:
```
make[1]: Entering directory '/src/agent'
go test ./... -v -count=1 -race
```

Going to close but please re-open if I'm missing where we are running it without race enabled.
