### ISSUE TITLE
VcpuCount should be configurable per VM

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker-containerd#359]
Currently the `Config` structure has a set of machine configuration options, like `VcpuCount`, that probably should be apart of the `CreateVMRequest` similarly to how `MemSizeMib` is used.

This task should remove Vcpu count from the `Config` and make it consistent to how `MemSizeMib` is used since we probably want this configurable per VM as opposed to a global configuration.

**Comment by Zyqsempai** [comment]
I can take this one!

**Comment by xibz** [comment]
Hello @Zyqsempai, that would be very helpful! This one should be straightforward! But if you have any question, please let us know :).

**Comment by Zyqsempai** [comment]
@xibz Hmm, looks like it's already done;)
https://github.com/firecracker-microvm/firecracker-containerd/blob/master/proto/types.pb.go#L442

**Comment by xibz** [comment]
@Zyqsempai - That is for the request. There is an inconsistency with how [`MemSizeMib`](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/runtime/helpers.go#L37) and [`VcpuCount`](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/config/config.go#L86) is handled in configuration. There are two solutions to make this consistent, either we can remove `VcpuCount` from the [`Config` structure](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/config/config.go#L40-L59), or we can add `MemSizeMib` to the `Config.

I think I prefer removing it from the `Config` object all together, but I am open to the other solution as well.

**Comment by kzys** [comment]
Fixed by #372. Thanks @Zyqsempai!
