### ISSUE TITLE
"failed to release stub drive for container" error for stopping container

### ISSUE THREAD

**Issue by haikuoliu** [firecracker-microvm/firecracker-containerd#370]
Full error: 

```
* failed to release stub drive for container: 3b95ef1f-202c-414b-8d9d-f1260790e683: failed to unmount drive: rpc error: code = NotFound desc = method UnmountDrive
```

I am using latest firecracker containerd, and I launched a VM with jailer, the VM was running, then I launched a container that sleeps forever, when I tried to kill the container, I got error above. I was using AmazonLinux 2 rootfs (writable) and it has latest fc-containerd agent installed.

Is that something to do with firecracker-containerd or the rootfs itself?

**Comment by kzys** [comment]
Can you rebuild your rootfs image from the latest source?

You got `code = NotFound desc = method UnmountDrive` and the UnmountDrive method is relatively new (added by #339). Your in-VM agent might not have the method.

**Comment by haikuoliu** [comment]
I just rebuilt the rootfs with the latest VM agent ([b95b5093ea5e44c42594aa922e593e02c3aa2438](https://github.com/firecracker-microvm/firecracker-containerd/commit/b95b5093ea5e44c42594aa922e593e02c3aa2438)), but still got same error. When my container exits itself (instead of being killed), it works normally, I think the stub drive should be released no matter of the container is killed or not right?

**Comment by haikuoliu** [comment]
Sorry my latest agent wasn't copied over to the al2 rootfs due to a bug in my build script, my bad, close this issue.
