### ISSUE TITLE
systemd and rootfs takes >1sec to start

### ISSUE THREAD

**Issue by ustiugov** [firecracker-microvm/firecracker-containerd#410]
Hi,

I started to investigate the issue with a very long startup time that we found out in #398 . From `dmesg` log I can say that systemd and rootfs seem to take nearly a second to bootstrap. 

I would be willing to put effort into investigating the issue further and/or fixing it but I would like to know your comments and feedback first. I hope to hear from the folks that have previously confirmed the issue (e.g., @kzys, @IRCody  and @mxpv ).

I understand that firecracker-containerd relies on systemd to start the agent at the VM startup time (described [here](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/tools/image-builder/README.md))

```
[    0.080562] Freeing unused kernel memory: 584K
[    0.258537] systemd[1]: Failed to lookup module alias 'autofs4': Function not implemented
[    0.261983] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    0.262008] systemd[1]: Detected virtualization kvm.
[    0.262011] systemd[1]: Detected architecture x86-64.
[    0.265433] systemd[1]: Set hostname to <microvm>.
[    0.359270] systemd-system-update-generator[471]: Offline system update overridden by kernel command line systemd.unit= setting
[    0.422642] systemd[1]: rom.mount: Unit is bound to inactive unit dev-vda.device. Stopping, too.
[    0.434441] systemd[1]: Starting of Arbitrary Executable File Formats File System Automount Point not supported.
[    0.435665] systemd[1]: Created slice system-getty.slice.
[    0.435741] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    0.435762] systemd[1]: Reached target Slices.
[    0.435929] systemd[1]: Listening on Journal Audit Socket.
[    0.438262] systemd[474]: rom.mount: Failed to connect stdout to the journal socket, ignoring: No such file or directory
[    0.544512] random: systemd-random-: uninitialized urandom read (512 bytes read)
[    0.606687] systemd-journald[480]: Received request to flush runtime journal from PID 1
[    1.056186] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x23f3e9a353a, max_idle_ns: 440795330815 ns
[    1.247684] virtio_blk virtio1: new size: 20971520 512-byte logical blocks (10.7 GB/10.0 GiB)
[    1.247688] vdb: detected capacity change from 512 to 10737418240
[    1.308528] EXT4-fs (vdb): mounted filesystem with ordered data mode. Opts: (null)
[    1.325922] random: fast init done
[    1.363873] random: crng init done
```

To reproduce the issue:
```
sudo firecracker-ctr --address /run/firecracker-containerd/containerd.sock   run   --snapshotter devmapper   --runtime aws.firecracker   --rm --tty --net-host docker.io/library/nginx:1.17-alpine test dmesg
```

Guest kernel boot args:
```
console=ttyS0 noapic reboot=k panic=1 pci=off nomodules ro systemd.journald.forward_to_console systemd.unit=firecracker.target init=/sbin/overlay-init tsc=reliable quiet 8250.nr_uarts=0 ipv6.disable=1
```

**Comment by IRCody** [comment]
Hey @ustiugov. Sorry for the delay in responding.

We are definitely interested in improving the startup time and would welcome your help investigating/fixing any issues that are slowing down startup. What do you see as the best areas to investigate or that show the potential for the largest improvement?

**Comment by ustiugov** [comment]
@IRCody sure, I'd be happy to contribute. 

First of all, I would try to understand what in the rootfs configuration degrades the startup time **10x** vs. what was demonstrated in [firecracker-demo](https://github.com/firecracker-microvm/firecracker-demo) (1.3sec vs 125ms). I observe this long boot time on both Alpine and Ubuntu guest, no kernel modules. Is there something we could do with kernel configuration or boot parameters changes?

I tried to use `systemd-analyze time` on Ubuntu but it did not work for me. I would appreciate ideas on rootfs load process troubleshooting. Unfortunately, I don't have experience in system boot time analysis.

**Comment by IRCody** [comment]
One of the differences between our default and firecracker-demo is that their bootargs don't include a [console](https://github.com/firecracker-microvm/firecracker-demo/blob/c22499567b63b4edd85e19ca9b0e9fa398b3300b/start-firecracker.sh#L9) while our [default](https://github.com/firecracker-microvm/firecracker-containerd/blob/f30a5ac8bb95e97ecbbd6cb6b6af538beeff4df2/config/config.go#L32) one does. Might be a place to start looking/experimenting.

**Comment by ustiugov** [comment]
@IRCody thank you, I tried to remove `console=ttyS0 systemd.journald.forward_to_console` but `dmesg` does not show any noticeable improvement in a startup time.

**Comment by ustiugov** [comment]
@kzys any ideas for further investigation? thank you in advance

**Comment by kzys** [comment]
I made a rootfs without systemd (#429) as an experiment. We may not use that in production, but would be helpful to understand the baseline performance.

**Comment by kzys** [comment]
While I could reproduce the issue before (https://firecracker-microvm.slack.com/archives/CEBSNEPDX/p1582850086013500?thread_ts=1582767117.008700&cid=CEBSNEPDX), the numbers are much better now. Can you take a look #430?

**Comment by ustiugov** [comment]
thank you! I left a comment there: I am trying to reproduce the ~500ms startup time but running into a problem. 

Do you know what changed in the firecracker-containerd code or boot procedure that led to that speedup? I am trying to understand the minimum startup time for a production setup. 

Btw, with my docker images and latest firecracker-containerd, I still get 1.3 seconds going into calling the VM-internal agent...

**Comment by ustiugov** [comment]
@kzys forgot the name tag, sorry

**Comment by kzys** [comment]
@ustiugov What is your host's spec? I (and probably most of AWS folks there) tend to use m5d.metal EC2 instance.

**Comment by ustiugov** [comment]
@kzys sorry for the late response. I am using a server-grade Intel Xeon Broadwell (E5-2680 v3) with 246GB RAM and SSD. I think that

**Comment by kzys** [comment]
@ustiugov Regarding the issue you've mentioned in #429, CreateVM now can take TimeoutInSeconds parameter. Does it work for you?

**Comment by ustiugov** [comment]
Thank you, @kzys . Could you please specify how should I pass that parameter to the test? I am going to document that later. 
To me, what happens is that all the subtests reach their 5-sec timeout which should not be the case if the firecracker-containerd daemon worked properly.

**Comment by kzys** [comment]
Please add `TimeoutSeconds` (added by 66951e26a13b5c1d18d6158a15b2a6d9f02bfcb8) in below.

https://github.com/firecracker-microvm/firecracker-containerd/blob/5b51e6f5bd9fc98b57cdef78eba6eb5a2cf2cf14/runtime/benchmark_test.go#L71

**Comment by ustiugov** [comment]
I tried setting that parameter to 3 and 7 seconds but in all cases I got the same exact log: `context deadline exceeded` after 5 seconds.

**Comment by ustiugov** [comment]
sorry, forgot the tag again @kzys

**Comment by kzys** [comment]
Can you check firecracker-containerd's logs? With `log_levels:["debug"]`, you should be able to see Firecracker's console log there as well. Taking 5 seconds doesn't seem normal.

**Comment by ustiugov** [comment]
@kzys I've set the following parameters in both configs but I do not observe any logs on the screen (the output of `make -C ...` is the same):

/etc/firecracker-containerd/config.toml
```
...
[debug]
  level = "debug"
```

/etc/containerd/firecracker-runtime.json
```
{
  "firecracker_binary_path": "/usr/local/bin/firecracker",
  "cpu_template": "T2",
  "log_fifo": "fc-logs.fifo",
  "log_level": "Debug",
...
}
```

**Comment by ustiugov** [comment]
@kzys 
apparently, the getting-started guide contains obsolete names of the fields (the correct ones are "log_levels" and "debug"). 

Eventually, I figured that the test writes the log to:
```
$REPO_PATH/runtime/logs/containerd.out
```

It seems that there is a problem with connecting to the agent inside the VM:
```level=debug attempt=5 error="temporary vsock dial failure: vsock ack message failure: EOF" runtime=aws.firecracker vmID=6dfc130f-1223-4323-8d8c-808b2042c845```

[Full log](https://gist.github.com/ustiugov/e5a15f62f272823bd611909eabe989bc)

Do you have any idea what could be the problem?

**Comment by kzys** [comment]
Sorry about the doc. I will update the section soon.

Regarding the log, you have launched a VM successfully.

```
time="2020-07-10T11:08:52.404012028Z" level=debug msg="[    1.493951] agent[704]: time=\"2020-07-10T11:08:52Z\" level=info msg=\"creating task service\"" jailer=noop runtime=aws.firecracker vmID=6dfc130f-1223-4323-8d8c-808b2042c845 vmm_stream=stdout
time="2020-07-10T11:08:52.459904446Z" level=info msg="successfully started the VM" runtime=aws.firecracker vmID=6dfc130f-1223-4323-8d8c-808b2042c845
time="2020-07-10T11:08:52.460036071Z" level=debug msg="event published" ns=default runtime=aws.firecracker topic=/firecracker-vm/start type=VMStart
time="2020-07-10T11:08:52.460536606Z" level=debug msg="event forwarded" ns=default topic=/firecracker-vm/start type=VMStart
```

And then stopping the VM.

```
time="2020-07-10T11:08:52.461650794Z" level=debug msg="stop VM: VMID:\"6dfc130f-1223-4323-8d8c-808b2042c845\" "
time="2020-07-10T11:08:52.462096325Z" level=debug msg=StopVM runtime=aws.firecracker timeout_seconds=0 vmID=6dfc130f-1223-4323-8d8c-808b2042c845
time="2020-07-10T11:08:52.462142206Z" level=info msg="stopping the VM" runtime=aws.firecracker vmID=6dfc130f-1223-4323-8d8c-808b2042c845
```

I assume that you didn't have any errors, but just wondering why it was slow. Right?

**Comment by ustiugov** [comment]
@kzys thank you. Here is what I get now:
```
/home/ustiugov/firecracker-containerd/runtime/../tools/thinpool.sh reset ""
docker run --rm -it \
        --privileged \
        --ipc=host \
        --network=none \
        --volume /dev:/dev \
        --volume /run/udev/control:/run/udev/control \
        --volume /home/ustiugov/firecracker-containerd/runtime/logs:/var/log/firecracker-containerd-test \
        --volume /home/ustiugov/firecracker-containerd/runtime/..:/src \
        --volume gocache:/go \
        --env ENABLE_ISOLATED_TESTS=1 \
        --env FICD_DM_VOLUME_GROUP= \
        --env FICD_DM_POOL= \
        --env GOPROXY=direct \
        --env GOSUMDB=off \
        --env NUMBER_OF_VMS= \
        --workdir="/src/runtime" \
        --init \
        localhost/firecracker-containerd-test:latest \
        "go test -v -run 'TestPerf_CreateVM'"
=== RUN   TestPerf_CreateVM
=== RUN   TestPerf_CreateVM/vcpu=1
=== RUN   TestPerf_CreateVM/vcpu=5
=== RUN   TestPerf_CreateVM/firecracker-demo
--- PASS: TestPerf_CreateVM (212.77s)
    --- PASS: TestPerf_CreateVM/vcpu=1 (73.05s)
        benchmark_test.go:96: TestPerf_CreateVM/vcpu=1: avg:1.77244561s samples:[1.689397871s 1.796608518s 1.692086292s 1.792605258s 1.789875881s 1.791981739s 1.794020344s 1.796818321s 1.79107512s 1.789986759s]
    --- PASS: TestPerf_CreateVM/vcpu=5 (72.64s)
        benchmark_test.go:96: TestPerf_CreateVM/vcpu=5: avg:1.782454562s samples:[1.793805969s 1.789859475s 1.784365351s 1.794323283s 1.694441404s 1.794686057s 1.79300778s 1.797727788s 1.790353674s 1.79197484s]
    --- PASS: TestPerf_CreateVM/firecracker-demo (67.07s)
        benchmark_test.go:96: TestPerf_CreateVM/firecracker-demo: avg:1.312999615s samples:[1.290399123s 1.297929514s 1.290217962s 1.292061523s 1.292756168s 1.294361026s 1.393107767s 1.296203939s 1.392590962s 1.290368172s]
PASS
ok      github.com/firecracker-microvm/firecracker-containerd/runtime   212.822s

```

Looks like that the startup time is much worse than what you reported... I wonder what could be the reason for this 2-3x difference

**Comment by ustiugov** [comment]
I think we can close this issue

**Comment by elchead** [comment]
@ustiugov did you find out the reason?

**Comment by ustiugov** [comment]
@elchead not beyond what we discussed in this Issue
