### ISSUE TITLE
Remove shim directories correctly

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker-containerd#415]

**Comment by kzys** [comment]
I'd like to add some tests to prevent this regression. Let me keep the issue open.

**Comment by FFMMM** [comment]
The are scenarios at runtime:

* running w a jailer
* running w a noop jailer

At present, both of these code paths are tested for sync shim dir removal. For the noop jailer code path testing, please refer to [these lines](https://github.com/firecracker-microvm/firecracker-containerd/blob/4e4c9073d5704588a4ea3d98fcd84071f571b478/runtime/jailer_integ_test.go#L41-L44).

As such, this issue will be closed

----

Further work could involve checking namespace dir removal. This work is being scoped in https://github.com/firecracker-microvm/firecracker-containerd/issues/488 .
