### ISSUE TITLE
Add cgroup path on GetVMInfoResponse

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker-containerd#416]

**Comment by xibz** [comment]
And cgroup path is returned with get vm info.

**Comment by kzys** [comment]
Oh, right. (cc @ofiliz)

https://github.com/firecracker-microvm/firecracker-containerd/blob/8b08d11c7598a3884af3f63cb2cbbf03ac4336de/proto/firecracker.proto#L61

**Comment by ofiliz** [comment]
The field is there, but not set.

https://github.com/firecracker-microvm/firecracker-containerd/blob/f30a5ac8bb95e97ecbbd6cb6b6af538beeff4df2/runtime/service.go#L600

**Comment by kzys** [comment]
#418 will fix this issue.
