### ISSUE TITLE
No longer builds against Go Firecracker SDK

### ISSUE THREAD

**Issue by nmeyerhans** [firecracker-microvm/firecracker-containerd#47]
The Go Firecracker SDK has recently changed some interfaces. In order to support Firecracker 0.12, we need to update to support the new SDK.

**Comment by mxpv** [comment]
Looks like fixed and merged in https://github.com/firecracker-microvm/firecracker-containerd/pull/49
So closing this, but feel free to reopen if something else needs to be done.
