### ISSUE TITLE
Error with quickstart and suggestion on docker dependency

### ISSUE THREAD

**Issue by alexellis** [firecracker-microvm/firecracker-containerd#472]
There are two things this issue is about:

1) There is an error with the Quickstart that I cannot get past yet, when using Ubuntu
2) The dependency on Docker is confusing since Docker and containerd ship very different (incompatible) versions of containerd

I was chatting to @estesp about trying to get [faasd](https://github.com/openfaas/faasd) (based upon containerd) to work with firecracker, however I was surprised to see [that Docker is required to do a build of the containerd binary](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/docs/quickstart.md).

Quite often Docker and containerd ship with different binaries that aren't compatible, so is the idea that I should build on my workstation and copy over to a server which has a stand-alone version of the tools on it?

I'd much prefer being able to build then deploy to the same Linux host where I'll be testing out firecracker. This indirection is causing some friction and confusion for me.

Hope this is useful feedback on some level.

**Comment by alexellis** [comment]
This is the last command that worked in the quickstart.

```
root@firecracker:/var/lib/firecracker-containerd/snapshotter/devmapper# if ! $(sudo dmsetup reload "${POOL}" --table "${THINP_TABLE}"); then
>     sudo dmsetup create "${POOL}" --table "${THINP_TABLE}"
> fi

device-mapper: reload ioctl on fc-dev-thinpool  failed: No such device or address
Command failed.
```

System details (on Packet/Equinix Metal)

```
root@firecracker:~# uname -a
Linux firecracker 5.8.0-26-generic #27-Ubuntu SMP Wed Oct 21 22:29:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@firecracker:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
root@firecracker:~# 
```

**Comment by alexellis** [comment]
Here are the equivalent setup instructions for Ubuntu for the initial setup of Docker and Go 1.15.

```bash
curl -4 -o go.tgz -SL https://golang.org/dl/go1.15.8.linux-amd64.tar.gz

mkdir /usr/local/go

tar -xvf go.tgz --strip-components=1 -C /usr/local/go

sudo apt update && sudo apt install -qy   make   git   curl   e2fsprogs   util-linux   bc   gnupg

export PATH=$PATH:/usr/local/go/bin

sudo usermod -aG docker $(whoami)
curl -sLS https://get.docker.com | sh

sudo apt install build-essential -qy
```

The rest should be identical from `# Check out firecracker-containerd and build it.` onwards.

**Comment by kzys** [comment]
Sorry for the confusion. If you just want to build firecracker-containerd, you can do that without Docker. `make` (or `make all`) build all binaries on the host itself.

However the root filesystem creation and automated test related targets depend on Docker right now.

**Comment by alexellis** [comment]
@kzys I installed Docker, but as you can see there are vsock errors after following the instructions with Ubuntu.

I appreciate you responding, but this doesn't unblock me. Can you verify that this project is functioning on Ubuntu Linux?

**Comment by samuelkarp** [comment]
Hey @alexellis!

> Quite often Docker and containerd ship with different binaries that aren't compatible, so is the idea that I should build on my workstation and copy over to a server which has a stand-alone version of the tools on it?
>
> I'd much prefer being able to build then deploy to the same Linux host where I'll be testing out firecracker. This indirection is causing some friction and confusion for me.

The quickstart is designed to let you build and run on the same Linux host where you're testing Firecracker.  We use separate binaries to avoid conflicts with Docker.

I looked in the [gist](https://gist.github.com/alexellis/e9d0671e4c9602fca598d7cc9f4f58c7) you provided and found this line, which looks to be the relevant culprit:

```
[    0.599754] agent[716]: /usr/local/bin/agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/agent)
```

It looks like the agent binary was not built with the `STATIC_AGENT` environment variable and it's instead trying to link against the glibc present on your Ubuntu host rather than the glibc present in the Debian microVM image (even though the Makefile [sets that variable](https://github.com/firecracker-microvm/firecracker-containerd/blob/cc8679645a385ccebc40564f22528fe8af21ba99/Makefile#L63)).  We usually build the agent as statically-linked to avoid this problem.  Did you build the agent binary before installing Docker?  I wonder if our Makefile isn't cleaning up and rebuilding when it should be.

Can you try rebuilding the image and reinstalling it to the correct location (should be `sudo cp ~/firecracker-containerd/tools/image-builder/rootfs.img /var/lib/firecracker-containerd/runtime/default-rootfs.img` if you followed the quickstart)?  `make image` might do it alone, but if it doesn't you'll want to `make clean image` (which will take longer since it'll rebuild everything).

You might also find the [getting started guide](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/docs/getting-started.md) to be helpful as it steps through the requirements in more detail.

It's late for me here, but I'm happy to help more in the morning (my time).

Sam

**Comment by alexellis** [comment]
Thanks for the pointers. I just followed the quick-start verbatim, with the modification for a newer Docker CE version and a newer Golang version.

When running this step, I get the following error:

```
~/firecracker-containerd# sudo DEBIAN_FRONTEND=noninteractive apt-get install -y dmsetup
```

> fatal: Not a git repository: ../../.git/modules/runc
> fatal: Not a git repository: ../../.git/modules/runc

**Comment by alexellis** [comment]
Running this block gave me an error again, just like when I did this with Ubuntu Linux. I have a feeling that the instructions are not complete or are missing a step.

<img width="1118" alt="Screenshot 2021-02-19 at 10 04 16" src="https://user-images.githubusercontent.com/6358735/108489783-e3106f80-7299-11eb-94a9-ec466c3b6bf9.png">


```
root@firecracker-debian10:/var/lib/firecracker-containerd/snapshotter/devmapper# 
root@firecracker-debian10:/var/lib/firecracker-containerd/snapshotter/devmapper# if ! $(sudo dmsetup reload "${POOL}" --table "${THINP_TABLE}"); then
>     sudo dmsetup create "${POOL}" --table "${THINP_TABLE}"
> fi
device-mapper: reload ioctl on fc-dev-thinpool  failed: No such device or address
Command failed.
root@firecracker-debian10:/var/lib/firecracker-containerd/snapshotter/devmapper# 
root@firecracker-debian10:/var/lib/firecracker-containerd/snapshotter/devmapper# 
```

**Comment by alexellis** [comment]
After re-running several of the commands I got a VM to launch through `ctr run!`

This message was printed out by containerd, but I don't know if it's an error

```
DEBU[2021-02-19T10:07:03.428545928Z] [    1.471698] systemd[756]: serial-getty@ttyS0.service: Executable /sbin/agetty missing, skipping: No such file or directory  jailer=noop runtime=aws.firecracker vmID=f7ac9a76-637a-4fb0-ac9c-8d933fabc4ab vmm_stream=stdout
```

**Comment by kzys** [comment]
That's great. I think the getty one is fine. Let me take a look.

Regarding your previous comments;

- Getting `fatal: Not a git repository: ../../.git/modules/runc` from apt-get is really odd. apt-get must not call Git.
- `sudo dmsetup reload "${POOL}" --table "${THINP_TABLE}"` would fail if you don't have the thin-pool but then `sudo dmsetup create "${POOL}" --table "${THINP_TABLE}"` will create the thin-pool. Can you check `dmsetup ls` on your host?

**Comment by kzys** [comment]
FYI, the getty error is fixed in master. Thanks for reporting!

**Comment by alexellis** [comment]
🙏  thank you

I'm having issues with CNI, I had hoped to find a quickstart that I could drop in and use with the [faasd code](https://github.com/openfaas/faasd/blob/master/pkg/cninetwork/cni_network.go#L113). I would appreciate some pointers or examples.

I tried to create a minimal example that someone on the team can run to see the issues with using CNI and the PID netns (the PID isn't found because it appears to be from the VM, and not readable from where containerd is running on the host)

Thanks to @samuelkarp for giving some pointers on Slack. I'm at a bit of a dead-end now though.

**Comment by sgaist** [comment]
Hi @alexellis, since you closed this ticket, should I abandon my pull request ?
