### ISSUE TITLE
StopVM must not stuck when the VM itself is paused

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker-containerd#492]
Right now StopVM calls an agent inside the VM. However after having pause/resume, the VM could be paused. In that case, StopVM will stuck since it cannot establish the connection to the VM.

We may need to either

- Implicitly resume the VM
- Kill the VM without resuming

Or consider 
- returning an error when the VM is in that state.

In addition to that, StopVM has "force kill" which SIGKILL the Firecracker process. Why didn't it work on #487?

**Comment by alakesh** [comment]
We can do the following:
1. Detect if the VM is in paused
2. If the VM is paused, then resume and remount its FS readonly ( to prevent data corruption )
3. Force kill the VM ( if that works ).

Meanwhile to be able to do that we need api to obtain VM's running state.  Following PR would facilitate this if approved
https://github.com/firecracker-microvm/firecracker-go-sdk/pull/338

**Comment by RoyceDavison** [comment]
Isn't the vm running state information stored in machineConfig? https://github.com/firecracker-microvm/firecracker-containerd/blob/f320d3636aee41661eb525b284ce6213f6c7a3d5/runtime/service.go#L679

**Comment by alakesh** [comment]
> Isn't the vm running state information stored in machineConfig? How about call GetVMInfo()?
> 
> https://github.com/firecracker-microvm/firecracker-containerd/blob/f320d3636aee41661eb525b284ce6213f6c7a3d5/runtime/service.go#L679

It does not return the VM state [ running/paused/resumed ].

**Comment by alakesh** [comment]
Was thinking, if this issue can only happen with StopVM. Ideally any call that depends on the agent running inside the VM would need to check if the VM is running. @kzys? If that is the case, this issue would be a good place to address all such cases.

**Comment by alakesh** [comment]
With PR #500 PR #502  and PR #519  merged, this issue can be closed.
