### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker-containerd#496]
We're making changes across the `firecracker-microvm` org to use inclusive language in documentation, code and branch naming.

This issue tracks renaming https://github.com/firecracker-microvm/firecracker-containerd `master` branch to `main`.

**Comment by RoyceDavison** [comment]
Created a pr for this https://github.com/firecracker-microvm/firecracker-containerd/pull/499

**Comment by RoyceDavison** [comment]
Merged the PR #499
