### ISSUE TITLE
ctr: start failed: aws.firecracker: unexpected error from CreateVM: rpc error: code = Unknown desc = failed to create VM: failed to start the VM: Put http://localhost/actions: EOF : exit status 1: unknown

### ISSUE THREAD

**Issue by romen10** [firecracker-microvm/firecracker-containerd#535]
**Experiment with firecracker and firecracker-containerd**

1.use VirtualBox install firecracker and firecracker-containerd；
2.follow doc like this https://github.com/firecracker-microvm/firecracker-containerd/blob/main/docs/quickstart.md;

This doc does not require KVM to be installed. Do you need to install KVM before this document?

exec successed：“sudo firecracker-containerd --config /etc/firecracker-containerd/config.toml” and “sudo firecracker-ctr --address /run/firecracker-containerd/containerd.sock \
     image pull \
     --snapshotter devmapper \
     docker.io/library/debian:latest”

when exec this command-lines "sudo firecracker-ctr --address /run/firecracker-containerd/containerd.sock \
     run \
     --snapshotter devmapper \
     --runtime aws.firecracker \
     --rm --tty --net-host \
     docker.io/library/debian:latest \
     test"
, error like this:
"ctr: start failed: aws.firecracker: unexpected error from CreateVM: rpc error: code = Unknown desc = failed to create VM: failed to start the VM: Put http://localhost/actions: EOF
: exit status 1: unknown"
firecracker-containerd console errors like this :
"DEBU[2021-08-15T02:01:53.724425488+08:00] Running handler fcinit.AddVsocks              runtime=aws.firecracker
DEBU[2021-08-15T02:01:53.747545337+08:00] Attach vsock firecracker.vsock successful: [PUT /vsock][204] putGuestVsockNoContent   runtime=aws.firecracker
DEBU[2021-08-15T02:01:53.747590043+08:00] Running handler firecracker-containerd-jail-pid-handler  runtime=aws.firecracker
ERRO[2021-08-15T02:01:54.590719022+08:00] Starting instance: Put http://localhost/actions: EOF  runtime=aws.firecracker
WARN[2021-08-15T02:01:54.591256649+08:00] firecracker exited: signal: aborted (core dumped)  runtime=aws.firecracker
DEBU[2021-08-15T02:01:54.698511905+08:00] sending signal 9 to 11704                     jailer=noop runtime=aws.firecracker vmID=21b13ea9-b693-459b-8b80-be3ccd378a13
ERRO[2021-08-15T02:01:54.698645904+08:00] failed to create VM                           error="failed to start the VM: Put http://localhost/actions: EOF" runtime=aws.firecracker vmID=21b13ea9-b693-459b-8b80-be3ccd378a13
DEBU[2021-08-15T02:01:54.698609918+08:00] closing the exitCh 1 error occurred:
	* signal: aborted (core dumped)
  runtime=aws.firecracker
DEBU[2021-08-15T02:01:54.698691282+08:00] stopVMM(): sending sigterm to firecracker     runtime=aws.firecracker
ERRO[2021-08-15T02:01:54.722204236+08:00] shim CreateVM returned error                  error="rpc error: code = Unknown desc = failed to create VM: failed to start the VM: Put http://localhost/actions: EOF"
ERRO[2021-08-15T02:01:54.724238278+08:00] copy shim log                                 error="read /proc/self/fd/11: file already closed"
DEBU[2021-08-15T02:01:54.733507391+08:00] shim has been terminated                      error="signal: killed" vmID=21b13ea9-b693-459b-8b80-be3ccd378a13
DEBU[2021-08-15T02:01:54.734637947+08:00] remove snapshot                               key=test"

**Comment by RoyceDavison** [comment]
Could you provide the following configs? 
`sudo cat /etc/firecracker-containerd/config.toml` and `sudo cat /etc/containerd/firecracker-runtime.json`

**Comment by romen10** [comment]
Thank you ,RoyceZ! I know the reason that i would not switch on the nested virtualization of virtualbox. now run the firecracker-containerd successful.
