### ISSUE TITLE
Simplify the runtime configuration

### ISSUE THREAD

**Issue by samuelkarp** [firecracker-microvm/firecracker-containerd#59]
The runtime configuration is fairly complicated and has a number of fields that need reasonable defaults.

* ~`firecracker_binary_path` - the relative path default is unreasonable, since the working directory changes every time containerd executes a new container (working directory is inside the container bundle)~
* [x] `socket_path` - needs a reasonable default, probably relative inside the working directory/bundle
* [x] `kernel_image_path` - could use a default lookup path
* [x] `kernel_args` - needs a reasonable default
* [x] `root_drive` - could use a default lookup path
* [x] `cpu_count` - might want to pick this dynamically from the OCI spec, with perhaps a reasonable default
* ~`console` - should it default to "stdio"?~

Related to https://github.com/firecracker-microvm/firecracker-containerd/issues/57

**Comment by IRCody** [comment]
>socket_path - needs a reasonable default, probably relative inside the working directory/bundle

Not sure about all the others but I think `./firecracker.sock` makes sense as a default for socket_path.

**Comment by samuelkarp** [comment]
> Not sure about all the others but I think ./firecracker.sock makes sense as a default for socket_path.

Yep, I think so too.

**Comment by xibz** [comment]
I believe the jailer socket path (not settable) is `api.socket` and in firecracker's doc they use `firecracker.socket` every where. Should we try to be consistent? If the jailer is on by default, may be best to go with `api.socket`?

**Comment by samuelkarp** [comment]
> `firecracker_binary_path` - the relative path default is unreasonable, since the working directory changes every time containerd executes a new container (working directory is inside the container bundle)

This has been changed in firecracker-go-sdk and we've now inherited that change such that it defaults to `firecracker` on `$PATH`.  This is a much more reasonable default.  I'll remove this item from the overview list.

**Comment by samuelkarp** [comment]
> I believe the jailer socket path (not settable) is `api.socket` and in firecracker's docs they use `firecracker.socket` in their getting started guide. Should we try to be consistent? If the jailer is on by default, may be best to go with `api.socket`?

That [looks accurate](https://github.com/firecracker-microvm/firecracker/blob/v0.15.2/jailer/src/lib.rs#L386-L392).  I think for now I'm going to hard-code the socket (instead of making it configurable) as `./firecracker.sock`, but when we take a look at jailer integration (https://github.com/firecracker-microvm/firecracker-containerd/issues/122) we'll need to revisit this.

**Comment by samuelkarp** [comment]
> `kernel_args` - needs a reasonable default

Per discussion with @nmeyerhans, my plan is to use "console=ttyS0 noapic reboot=k panic=1 pci=off nomodules rw" as the default for now.

**Comment by samuelkarp** [comment]
> `console` - should it default to "stdio"?

This field was removed, I'll remove it from this list.

**Comment by samuelkarp** [comment]
Everything that I had outlined doing in the overview is now done, so resolving.

Any further runtime configuration changes should be a separate issue.
