### ISSUE TITLE
Demux Snapshotter Not Closing Remote Snapshotters on VM Shutdown

### ISSUE THREAD

**Issue by ginglis13** [firecracker-microvm/firecracker-containerd#651]
The demux snapshotter implements a Close method. We create a snapshotsapi from the demux snapshotter:

```
service := snapshotservice.FromSnapshotter(snapshotter)
```

`snapshotservice` does not implement a Close method, and it does not call `snapshotter.Close`, meaning we will not hit this code path. https://github.com/containerd/containerd/blob/3dbd6a2498f5ec5ffedb26bc377858abb5c9f32c/contrib/snapshotservice/service.go

Even if we did hit this code path, the in-VM snapshotter as a `proxy.RemoteSnapshotter`, which treats `Close` as a noop:

https://github.com/containerd/containerd/blob/c4e29027d42809417f237e4f1662501384dbb702/snapshots/proxy/proxy.go#L184-L186

**Comment by ginglis13** [comment]
I've also noticed that there are no paths to Evict a snapshotter from demux snapshotter's cache.

**Comment by austinvazquez** [comment]
Resolved with #662. Closing.
