### ISSUE TITLE
aws.firecracker runtime

### ISSUE THREAD

**Issue by mehrdadrad** [firecracker-microvm/firecracker-containerd#85]
Can anybody help me where the aws.firecracker defined as the below doc mentioned (part 6 last part)
https://github.com/firecracker-microvm/firecracker-containerd/blob/master/docs/quickstart.md
```
sudo /usr/local/bin/ctr image pull \
     --snapshotter firecracker-naive \
     docker.io/library/debian:latest
sudo /usr/local/bin/ctr run \
     --snapshotter firecracker-naive \
     --runtime aws.firecracker \
     --tty \
     docker.io/library/debian:latest \
     test
```

**Comment by xibz** [comment]
Hello @mehrdadrad, thank you for reaching out to us. The `aws.firecracker` is the shim ID found [here](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/runtime/main.go#L20). This will be in the `containerd-shim-aws-firecracker` binary that should be copied into the `/usr/local/bin` instructed in the guide. Are you running into an error with the quickstart guide?

**Comment by mehrdadrad** [comment]
@xibz thanks, no it worked!
